sharp_columns = [
    "timestamp",
    "harp",
    "USFLUX",
    "MEANGAM",
    "MEANGBT",
    "MEANGBZ",
    "MEANGBH",
    "TOTPOT",
    "TOTUSJZ",
    "TOTUSJH",
    "ABSNJZH",
    "SAVNCPP",
    "MEANPOT",
    "MEANSHR",
    "SHRGT45",
    "SIZE",
    "SIZE_ACR",
    "NACR",
    "NPIX",
    "MEANJZD",
    "MEANALP",
    "MEANJZH",
]

input_columns = [
    'timestamp',
    'harp',
    'USFLUX',
    'MEANGAM',
    'MEANGBT',
    'MEANGBZ',
    'MEANGBH',
    'TOTPOT',
    'TOTUSJZ',
    'TOTUSJH',
    'ABSNJZH',
    'SAVNCPP',
    'MEANPOT',
    'MEANSHR',
    'SHRGT45',
    'SIZE',
    'SIZE_ACR',
    'NACR',
    'NPIX',
    'MEANJZD',
    'MEANALP',
    'MEANJZH',
    'Gp_Long',
    'Gp_Short',
    'Gs_Long',
    'Gs_Short',
    'Electron S',
    'Electron 38-53',
    'Electron 175-315',
    'Protons keV S',
    'Protons keV 47-68',
    'Protons keV 115-195',
    'Protons keV 310-580',
    'Protons keV 795-1193',
    'Protons keV 1060-1900',
]
